### PR TITLE
Add progress bar and eta to train.py

### PR DESCRIPTION
**Pull request by gkielian**
Adds in some features we saw recently including eta for when training will complete and progress bars.

### CODE REVIEW

**Comment by gkielian** [comment]
I should note that only change was shifting the while True block one indent to the right.

And prefixing this with the Progress bar context.

This should really help by adding time estimates for when training should complete, and also looks nice : )

**Review by klei22 — APPROVED** [review]
Looks good

**Review by klei22 — APPROVED** [review]
After some cleaning, looks good.

Not sure why there are commit messages mixed in the commits...

**Comment by klei22** [comment]
The git diff looks incorrect for this PR; git might not have been able to track the changes...

Try adding changes to a fresh clone to remove chances that git lost where the changes are (which could make it merge incorrectly).

**Pull request closed without merging**
