### PR TITLE
Constmax with quantization

### PR DESCRIPTION
**Pull request by advancedengineering**
Only changed model.py, constmax with quantizaition will use Constmax_quan() function, you can run the test using scripts from exploration/constmax_training_quan.sh

### CODE REVIEW

**Comment by gkielian** [comment]
This looks really good! : D 
Also a milestone for the repo -- and give us more confidence that in silicon the model will behave as projected in simulation.

---

About the merge conflict -- seems I mixed in some csv-forecasting commits into some of the constantmax improvements.

I'll see if I can create just a PR for the csv-forecasting modifications: [87a5a69](https://github.com/ReaLLMASIC/nanoGPT/pull/46/commits/87a5a690a57b0d3da4c9d546d519194883c6e019) to [74ac551](https://github.com/ReaLLMASIC/nanoGPT/pull/46/commits/74ac551dc672991f835ebc0b8566f7fac4aa339d)

I'll add this pr soon, and this should remove some of the above merge conflicts.

**Comment by gkielian** [comment]
@advancedengineering Hmm, looks like the recent pull requests might have made it more difficult to merge.

I'm very eager to merge these changes in and will take a closer look into this later today.

**Comment by advancedengineering** [comment]
Thanks for the effort, anything I can help on my end?

**Comment by gkielian** [comment]
@advancedengineering 

Btw, I'm not sure if the strategy I mentioned earlier will work, (I tried something similar earlier, and has an issue when there are pending PR's). 

I'm going to try to rebase the changes here on top of pr #51 and work past the merge conflicts in cli.

**Comment by gkielian** [comment]
Closing as we merged this in via #52

**Pull request closed without merging**
